name: jenkins-test

services:
  controller:
    image: jenkins/jenkins:lts-jdk17
    networks:
      - jenkins-net
    ports:
      - "33853:8080"

  agent1:
    image: jenkins/ssh-agent:latest-jdk17
    env_file:
      - ./.env
    expose:
      - 22
    ports:
      - "33854:8080"
    networks:
      - jenkins-net
    depends_on:
      - controller
    environment:
      - 'JENKINS_AGENT_SSH_PUBKEY=${SSH_PUBKEY}'

networks:
  jenkins-net:
    driver: bridge

