name: saltyhana-db

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=saltyhanadb'
      - 'POSTGRES_PASSWORD=hana'
      - 'POSTGRES_USER=salty'
    ports:
      - '33333:5432'
  redis:
    image: 'redis:7.4.1-alpine3.20'
    ports:
      - '33334:6379'
