INSERT INTO icon (icon_image, name)
VALUES ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_1.png', 'card1'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_2.png', 'card2'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_3.png', 'card3'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_4.png', 'card4'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_5.png', 'card5'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_6.png', 'card6'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_amusementpark.png',
        'goal-amusementpark'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_anniversary.png',
        'goal-anniversary'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_beach.webp', 'goal-beach'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_beer.png', 'goal-beer'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_cake.png', 'goal-cake'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_car.png', 'goal-car'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_christmas.png',
        'goal-christmas'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_coffee.png', 'goal-coffee'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_cruise.png', 'goal-cruise'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_lobstar.png', 'goal-lobstar'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_money.webp', 'goal-money'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_party.png', 'goal-party'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_pet.png', 'goal-pet'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_phone.webp', 'goal-phone'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_shopping.webp', 'goal-shopping'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_ticket.webp', 'goal-ticket'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_travel.png', 'goal-travel')
;