INSERT INTO icon (icon_image, name, color)
VALUES ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_1.png', 'card1', '#E6F8E0'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_2.png', 'card2', '#f2f2f2'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_3.png', 'card3', '#FFF2E4'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_4.png', 'card4', '#F8E6E6'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_5.png', 'card5', '#E6F8F1'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/card_6.png', 'card6', '#EAF1FA'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_amusementpark.png',
        'goal-amusementpark', '#CBA5FF'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_anniversary.png',
        'goal-anniversary', '#FF87E5'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_beach.webp', 'goal-beach', '#9AD0FF'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_beer.png', 'goal-beer', '#FFD44F'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_cake.png', 'goal-cake', '#FFCD9C'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_car.png', 'goal-car', '#FFB7B7'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_christmas.png',
        'goal-christmas', '#91CF99'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_coffee.png', 'goal-coffee', '#E5BB99'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_cruise.png', 'goal-cruise', '#94CEEF'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_lobstar.png', 'goal-lobstar', '#EEA9AC'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_money.webp', 'goal-money', '#FFC33C'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_party.png', 'goal-party', '#FAC48D'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_pet.png', 'goal-pet', '#D3B1FF'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_phone.webp', 'goal-phone', '#B1B4C6'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_shopping.webp', 'goal-shopping', '#B5C8E1'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_ticket.webp', 'goal-ticket', '#79D569'),
       ('https://saltyhana-image-bucket.s3.ap-northeast-2.amazonaws.com/icon/goal_icon_travel.png', 'goal-travel', '#6582B0')
;