#!/bin/bash
branch="$(git branch --show-current)"
commits="$(git rev-list --all)"

if [ "$branch" = "main" ] || [ "$branch" = "develop" ] && [ "$commits" != "" ]; then
  echo "Stop! Commit on this branch is blocked."
  exit 1
fi