name: Slack Notification for PR Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Notify on PR request
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL_ID: ${{ secrets.MY_SLACK_CHANNEL_ID }}
          SLACK_ICON: ${{ secrets.SLACK_ICON }}
        run: |
          curl -X POST --data-urlencode "payload={\"channel\": \"$SLACK_CHANNEL_ID\",
          \"text\": \"New PR: <${{ github.event.pull_request.title }}|${{ github.event.pull_request.html_url }}> by ${{ github.event.pull_request.user.login }}.\",
          \"icon_emoji\": \":$SLACK_ICON:\"}" $SLACK_WEBHOOK_URL